# Generated by Django 5.1.6 on 2025-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenicdata',
            old_name='sentiment_intensity',
            new_name='sentiment_magnitude',
        ),
        migrations.RemoveField(
            model_name='scenicdata',
            name='transport_modes',
        ),
        migrations.AddField(
            model_name='scenicdata',
            name='transport_mode',
            field=models.CharField(blank=True, db_column='交通方式', max_length=255, null=True, verbose_name='交通方式'),
        ),
        migrations.AddField(
            model_name='scenicdata',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_column='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='timedata',
            name='scenic_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='景区ID'),
        ),
        migrations.AddField(
            model_name='timedata',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='景区类型'),
        ),
        migrations.AddField(
            model_name='timedata',
            name='weekdays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='适用工作日'),
        ),
        migrations.AlterField(
            model_name='scenicdata',
            name='comment_count',
            field=models.IntegerField(blank=True, db_column='评论数量', null=True, verbose_name='评论数量'),
        ),
        migrations.AlterField(
            model_name='scenicdata',
            name='min_price',
            field=models.CharField(blank=True, db_column='最低票价', max_length=50, null=True, verbose_name='最低票价'),
        ),
    ]
