# Generated by Django 5.1.6 on 2025-04-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenic_data', '0003_remove_timedata_type_timedata_date_range_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturalreliclevelprice',
            options={'verbose_name': '文物保护单位等级票价', 'verbose_name_plural': '文物保护单位等级票价'},
        ),
        migrations.AlterModelOptions(
            name='forestparklevelprice',
            options={'verbose_name': '森林公园等级票价', 'verbose_name_plural': '森林公园等级票价'},
        ),
        migrations.AlterModelOptions(
            name='geologicalparklevelprice',
            options={'verbose_name': '地质公园等级票价', 'verbose_name_plural': '地质公园等级票价'},
        ),
        migrations.AlterModelOptions(
            name='museumlevelprice',
            options={'verbose_name': '博物馆等级票价', 'verbose_name_plural': '博物馆等级票价'},
        ),
        migrations.AlterModelOptions(
            name='naturereservelevelprice',
            options={'verbose_name': '自然景区等级票价', 'verbose_name_plural': '自然景区等级票价'},
        ),
        migrations.AlterModelOptions(
            name='sceniclevelprice',
            options={'verbose_name': '景区等级票价', 'verbose_name_plural': '景区等级票价'},
        ),
        migrations.AlterModelOptions(
            name='wetlandlevelprice',
            options={'verbose_name': '湿地公园等级票价', 'verbose_name_plural': '湿地公园等级票价'},
        ),
    ]
