# Generated by Django 5.1.6 on 2025-04-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenic_data', '0004_alter_culturalreliclevelprice_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficdata',
            old_name='transport_mode',
            new_name='transport',
        ),
        migrations.RemoveField(
            model_name='scenicdata',
            name='transport_mode',
        ),
    ]
