# Generated by Django 5.1.6 on 2025-04-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionrecord',
            name='action_type',
            field=models.CharField(choices=[('login', '登录'), ('register', '注册'), ('search', '搜索'), ('view', '查看'), ('favorite', '收藏'), ('admin', '管理员操作'), ('profile_update', '修改个人信息')], max_length=20, verbose_name='操作类型'),
        ),
    ]
