# Generated by Django 5.1.6 on 2025-04-30 15:28

from django.db import migrations, models


def update_existing_records(apps, schema_editor):
    """
    更新现有的用户操作记录，按照用户要求进行归类：
    1. 删除`view`（查看）类型中的`查看景区词云图`和`查询附近景区`这两个内容
    2. 将`view_scenic_detail`类型归入`view_scenic_detail`类型
    3. 将`update_profile`和`reset_password`类型归入`profile_update`类型
    4. 删除`view`（查看）类型
    """
    UserActionRecord = apps.get_model('user_management', 'UserActionRecord')
    
    # 1. 删除查看景区词云图和查询附近景区的记录
    UserActionRecord.objects.filter(
        action_type='view',
        details__contains='查看景区词云图'
    ).delete()
    
    UserActionRecord.objects.filter(
        action_type='view',
        details__contains='查询附近景区'
    ).delete()
    
    # 2. 将view_scenic_detail归入view_scenic_detail（如果存在）
    UserActionRecord.objects.filter(
        action_type='view_scenic_detail'
    ).update(action_type='view_scenic_detail')
    
    # 3. 将update_profile和reset_password类型归入profile_update
    UserActionRecord.objects.filter(
        action_type='update_profile'
    ).update(action_type='profile_update')
    
    UserActionRecord.objects.filter(
        action_type__in=['reset_password', 'reset_password_request']
    ).update(action_type='profile_update')
    
    # 4. 删除其他view类型记录（不属于view_scenic_detail的）
    UserActionRecord.objects.filter(
        action_type='view'
    ).delete()

    # 5. 修复搜索类型，删除没有进行任何景区名或者筛选搜索的记录
    UserActionRecord.objects.filter(
        action_type='search',
        details__in=['搜索景区:', '搜索景区: ']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_useractionrecord_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionrecord',
            name='action_type',
            field=models.CharField(choices=[('login', '登录'), ('register', '注册'), ('search', '搜索'), ('favorite', '收藏'), ('admin', '管理员操作'), ('profile_update', '修改个人信息'), ('view_scenic_detail', '查看景区详情')], max_length=20, verbose_name='操作类型'),
        ),
        # 添加数据迁移操作
        migrations.RunPython(update_existing_records),
    ]
