# Generated by Django 5.1.6 on 2025-04-16 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', '调试'), ('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误'), ('CRITICAL', '严重')], default='ERROR', max_length=10, verbose_name='错误级别')),
                ('message', models.TextField(verbose_name='错误信息')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='错误追踪')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='请求路径')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='请求方法')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '系统错误日志',
                'verbose_name_plural': '系统错误日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
