# Generated by Django 5.1.6 on 2025-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_auto_20250416_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemerrorlog',
            name='error_type',
            field=models.CharField(choices=[('FRONTEND', '前端'), ('BACKEND', '后端')], default='BACKEND', max_length=10, verbose_name='错误类型'),
        ),
    ]
