# Generated by Django 5.1.6 on 2025-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0003_systemerrorlog_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemerrorlog',
            name='context_data',
            field=models.TextField(blank=True, null=True, verbose_name='上下文数据'),
        ),
        migrations.AlterField(
            model_name='systemerrorlog',
            name='error_type',
            field=models.CharField(choices=[('FRONTEND', '前端'), ('BACKEND', '后端'), ('DATABASE', '数据库'), ('NETWORK', '网络'), ('AUTH', '认证'), ('PERMISSION', '权限'), ('API', 'API错误'), ('VALIDATION', '数据验证'), ('TIMEOUT', '超时'), ('UNKNOWN', '未知类型')], default='BACKEND', max_length=15, verbose_name='错误类型'),
        ),
    ]
